// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXRWAzHn9FRSgmFAOQGrN_lMIQszxxcAw',
    appId: '1:293384886897:web:85d2999c3ff822e53fd9d0',
    messagingSenderId: '293384886897',
    projectId: 'meal-it-e1676',
    authDomain: 'meal-it-e1676.firebaseapp.com',
    storageBucket: 'meal-it-e1676.appspot.com',
    measurementId: 'G-N09VBSQRMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaWF-aS-Assp4Rp5a61QFCWqd8TjwJLZU',
    appId: '1:293384886897:android:502b30c4af6859623fd9d0',
    messagingSenderId: '293384886897',
    projectId: 'meal-it-e1676',
    storageBucket: 'meal-it-e1676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRvbsX62rtDUXAIs8ku5DzyTFdY7kv62M',
    appId: '1:293384886897:ios:65079aa01577f86b3fd9d0',
    messagingSenderId: '293384886897',
    projectId: 'meal-it-e1676',
    storageBucket: 'meal-it-e1676.appspot.com',
    iosClientId: '293384886897-40adh6613e06ebh63m0g1gjuv1e0hghn.apps.googleusercontent.com',
    iosBundleId: 'lk.mealit.mealIt',
  );
}
